project:
  type: website
  render:
    - "index.qmd"
  output-dir: docs


website:
  title: "Data Science Workflows with Posit tools - Python focus"
  description: "This one-day workshop provides an introduction to building Data Science workflows in Python using Posit's professional products."
  site-url: https://posit-conf-2023.github.io/ds-workflows-python
  repo-url: https://github.com/posit-conf-2023/ds-workflows-python
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - default
      - styles.css
    toc: true
    
fig-format: svg    