---
title: "Food Inspections Project Usage - Last `r as.numeric(Sys.getenv('DAYSBACK', 30))` Days"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
---
```{r preflight_check, results='asis', include=TRUE}
# ---------------------------------------------------------------------------
# this section is used to stop the report from rendering
# if important variables are missing (CONNECT_SERVER and CONNECT_API_KEY)
# ---------------------------------------------------------------------------
if (
  nchar(Sys.getenv("CONNECT_SERVER")) == 0 ||
  nchar(Sys.getenv("CONNECT_API_KEY")) == 0
) {
  print(htmltools::h4("ERROR: Variables Not Defined"))
  print(htmltools::div(
    "The CONNECT_SERVER and CONNECT_API_KEY",
    "environment variables are required in order for this report",
    "to pull usage data.",
    htmltools::br(),
    htmltools::br(),
    "Please define these variables",
    "and then re-run the report.",
    htmltools::br(),
    htmltools::br(),
    style = "max-width: 600px"
  ))
  knitr::knit_exit("Terminating the report early.")
}
```

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(DT)
library(plotly)
library(ggplot2)
library(shiny)
library(lubridate)
library(blastula)
library(prettyunits)
library(connectapi)
library(connectwidgets)
library(thematic)

thematic::thematic_rmd(font = "Open Sans")

days_back <- as.numeric(Sys.getenv("DAYSBACK", 30))

default_content_title <- "Unknown (Deleted Content?)"

report_from <- lubridate::today() - lubridate::ddays(days_back)

client <- connectapi::connect()
# Using connectwidgets to get content info because it's a little easier to filter by tags
project_content <- connectwidgets::connect() |> connectwidgets::content() |> by_tag(c("posit::conf(2023) R Workflows","R Workshop")) 

project_content_guids <- project_content |> pull(guid)

shiny <- get_usage_shiny(
  client,
  from = report_from,
  limit = Inf,
  content_guid = project_content_guids
) %>%
  mutate(
    started = lubridate::ymd_hms(started),
    ended = lubridate::ymd_hms(ended),
    session_duration = ended - started
    ) %>%
  filter(session_duration > lubridate::dseconds(5))

content <- get_usage_static(
  client,
  from = report_from,
  limit = Inf,
  content_guid = project_content_guids
)

all_users <- get_users(client, page_size = 500)

data_arr <-   list(shiny = shiny, content = content)

```


This content summary may contain privileged information. The report is generated
using the [Posit Connect Server API](http://docs.posit.co/connect/api). Data is limited to the last 
`r days_back` days.


Column 
-----------------------------------------------------------------------


### Shiny Sessions Over Time

```{r shiny_over_time}
data_arr$shiny %>%
    mutate(day = round_date(started, "day")) %>% 
    filter(day > today() - ddays(days_back)) %>% 
    group_by(day) %>% 
    summarise(visits = n()) %>% 
    arrange(desc(visits)) %>% 
    {ggplot(., aes(day, visits)) + 
     geom_point() +
     geom_smooth(se = FALSE) +
     theme_minimal() +
     labs(
       y = "# of Shiny Sessions",
       x = NULL
     )} %>% 
    ggplotly(tooltip = c("y")) %>% 
    config(displayModeBar = F)
```

### Shiny Sessions by User (Top 20)

```{r shiny_by_user}
data_arr$shiny %>%
    group_by(user_guid) %>% 
    summarise(visits = n()) %>% 
    left_join(all_users, by = c(user_guid = "guid")) %>%
    mutate(username = coalesce(username, "anonymous")) %>%
    select(username, visits) %>% 
    arrange(desc(visits)) %>% 
    head(20) %>% 
    {ggplot(., aes(reorder(username, visits), visits, fill=username)) + 
     geom_bar(stat = "identity") +  
     coord_flip() + 
     theme_minimal() +
     labs(
       y = "Number of Shiny Sessions",
       x = NULL
     )} %>% 
    ggplotly(tooltip = c("y")) %>% 
    config(displayModeBar = F)
```


